# Generated by Django 4.2.10 on 2024-03-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("DEO", "Data Entry Operations"),
                            ("BC", "Basic Computing"),
                            ("HS", "Home Science"),
                            ("ENG", "English"),
                            ("PA", "Painting"),
                        ],
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(max_length=50)),
            ],
        ),
    ]
