# Generated by Django 4.2.10 on 2024-03-28 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee", "0002_alter_department_name_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                choices=[
                    ("PA", "Painting"),
                    ("HS", "Home Science"),
                    ("ENG", "English"),
                    ("DEO", "Data Entry Operations"),
                    ("BC", "Basic Computing"),
                ],
                max_length=50,
            ),
        ),
    ]
